Ansible 1
Otus-DevOps-2023-09/sergio21sem_infra pull request #7
Opened 2023-11-19 15:48 UTC by sergio21sem

# Выполнено ДЗ №

 - [ ] Основное ДЗ
 - [ ] Задание со *

## PR checklist
 - [ ] Выставил label с номером домашнего задания
 - [ ] Выставил label с темой домашнего задания

2023-11-19 15:55 UTC, mrgreyves requested changes
Здравствуйте!)
Проверил ваше дз
Рекомендую свериться с результатами тестов
Нужно многое поправить
ДЗ возвращаю на доработку

2023-11-19 16:13 UTC, sergio21sem commented
@mrgreyves не расчитывал, что так быстро вы будете смотреть) Нужно было повесить DRAFT

2023-11-19 16:16 UTC, sergio21sem commented
@mrgreyves забыл убрать кусок:
```#  required_providers {
#    yandex = {
#      source = "yandex-cloud/yandex"
#    }
#  }
#  required_version = ">= 0.13"```

Теперь можно проверять. Посмотрите, пожалуйста.
Кстати, нашел интересный пример дinamic inventory в репозитории вашей организации: https://github.com/express42/terraform-ansible-example/blob/master/ansible/dynamic_inventory.sh)

2023-11-21 08:19 UTC, mrgreyves approved these changes
Здравствуйте!)
С ДЗ все хорошо
Инвентарь можно формировать не только при помощи скриптов, но и с помощью темплейтов того же самого terraform =)
ДЗ принимаю =)

2023-11-24 16:25 UTC, merged